apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <APP_NAME>-home  # e.g. vscode-sandbox-home
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <STORAGE_CLASS>  # e.g. local-path
  resources:
    requests:
      storage: <STORAGE_SIZE>  # e.g. 10Gi
