services:
  vscode-sandbox:
    image: ghcr.io/whilcayangyang/whil-docker-images/vscode-sandbox:latest
    container_name: vscode-sandbox
    ports:
      - "2222:22"
    environment:
      AUTHORIZED_KEYS: "${AUTHORIZED_KEYS}"
    restart: unless-stopped
